name=snilb
all: tex

tex:
	pdflatex ${name}.tex
	pdflatex ${name}.tex
	# bibtex ${name}
	# pdflatex ${name}.tex
	# pdflatex ${name}.tex
clean:
	rm -rf *.aux *.out *.log *.nav *.snm *.toc *.bbl *.blg *.log *.bak
